public enum ItemTypeId
{
    NONE = 0,
    CLOTH_ARMOR = 1,
    LIGHT_ARMOR = 2,
    HEAVY_ARMOR = 3,
    MELEE_1H = 4,
    CONSUMABLE_POTIONS = 5,
    VALUABLE = 6,
    MELEE_2H = 7,
    RANGE = 8,
    HELMET = 9,
    SHIELD = 10,
    RECIPE_ENCHANTMENT_NORMAL = 14,
    RECIPE_ENCHANTMENT_MASTERY = 0xF,
    CONSUMABLE_MISC = 0x10,
    QUEST_ITEM = 17,
    RANGE_FIREARM = 18,
    CONSUMABLE_OUT_COMBAT = 19,
    MAX_VALUE = 20
}
