public enum ItemCategoryId
{
    NONE = 0,
    WEAPONS = 1,
    ARMOR = 2,
    CONSUMABLE_POTIONS = 3,
    RECIPE_ENCHANTMENT_NORMAL = 6,
    RECIPE_ENCHANTMENT_MASTERY = 7,
    QUEST_ITEM = 9,
    CONSUMABLE_MISC = 10,
    CONSUMABLE_OUT_COMBAT = 11,
    MAX_VALUE = 12
}
