public enum TrapTypeId
{
	NONE = 0,
	PILLAR_DECOR = 2,
	MADSTUFF_WALL = 3,
	MADSTUFF_BORDER = 4,
	SKAVEN_FLOOR = 5,
	MANTICORE_ACID = 6,
	SKILL_WYRDSTONE_LURE = 10,
	SKILL_WYRDSTONE_LURE_MSTR = 11,
	SKILL_BLACK_POWDER_TRAP = 12,
	SKILL_WHITE_POWDER_TRAP = 13,
	SKILL_DEATH_TRAP = 14,
	SKILL_DEATH_TRAP_MSTR = 0xF,
	SKILL_EYE_SEE_YOU = 0x10,
	SKILL_EYE_SEE_YOU_MSTR = 17,
	MAX_VALUE = 18
}
