public enum WarbandId
{
	NONE = 0,
	HUMAN_MERCENARIES = 1,
	SKAVENS = 2,
	SISTERS_OF_SIGMAR = 3,
	POSSESSED = 8,
	BLOODLETTERS = 12,
	PLAGUEBEARERS = 13,
	DAEMONETTES = 14,
	TZEENTCH_HORRORS = 0xF,
	DRAMATIS = 0x10,
	WITCH_HUNTERS = 17,
	UNDEAD = 18,
	MAX_VALUE = 19
}
